### ISSUE TITLE
Broken windows path creation

### ISSUE THREAD

**Issue by UserFromSpace** [PaaaulZ/CyberdropBunkrDownloader#12]
Hello, 

Issue: makedirs is not able to execute, returns error.
Tested on: Windows 10, Version 1703 and 22H2
Reproduce rate: 100%
Traceback (most recent call last):
  File "C:\Users\\Desktop\git\CyberdropBunkrDownloader-main\dump.py", line 151, in <module>
    get_items_list(args.u, args.e, args.s, args.i, args.w, args.p, args.ignore)
  File "C:\Users\\Desktop\git\CyberdropBunkrDownloader-main\dump.py", line 41, in get_items_list
    download_path = get_and_prepare_download_path(custom_path, album_name)
  File "C:\Users\\Desktop\git\CyberdropBunkrDownloader-main\dump.py", line 80, in get_and_prepare_download_path
    os.makedirs(final_path)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'downloads\\place | place | place'

**Comment by PaaaulZ** [comment]
Hi, can you give me the link you tried?
Thank you

**Comment by PaaaulZ** [comment]
I'll check it as soon as I can, thank you

**Comment by UserFromSpace** [comment]
For this very specific issue, I changed line 77 to:

`    final_path = final_path.replace('\n', '').replace('|', '')`

Not well versed with python, but there might a more universal approach.

**Comment by PaaaulZ** [comment]
This should be fixed with the new version, open the issue again if the problem comes back.
Thank you
