### ISSUE TITLE
Doesn't work on bunkr.si links

### ISSUE THREAD

**Issue by Shnxxx** [PaaaulZ/CyberdropBunkrDownloader#35]
```
Traceback (most recent call last):
  File "C:\Users\Shnxxx\Downloads\CyberdropBunkrDownloader-main\dump.py", line 188, in <module>
    get_items_list(args.u, args.e, args.w, args.p)
  File "C:\Users\Shnxxx\Downloads\CyberdropBunkrDownloader-main\dump.py", line 42, in get_items_list
    album_name = remove_illegal_chars(soup.find('h1', {'id': 'title'}).text)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by Shnxxx** [comment]
I noticed that when I opened a media in new tab, it changes its suffix to something. Like, bunkr.cat, bunkr.black, bunkr.ac, bunkr.media...

**Comment by neonnskye** [comment]
It definitely works on the latest version
