### ISSUE TITLE
Error When Downloading Certain Files

### ISSUE THREAD

**Issue by ItsBlunty** [PaaaulZ/CyberdropBunkrDownloader#36]
I'm getting the following error when trying to download certain videos from Bunkr. Some albums work fine, some run into errors with specific videos. Is this just something that is happening because of an issue on the Bunkr side? (I can currently view that video fine on the Bunkr site and download it)

```
PS G:\CyberdropBunkrDownloader-main> python3 dump.py -u https://bunkr.si/a/wE3paENr
        [+] Downloading https://burger.bunkr.ru/Ortega00---TG---@-(10)-isRMp7SG.mp4
Traceback (most recent call last):
  File "C:\Users\patri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\response.py", line 712, in _error_catcher
    yield
  File "C:\Users\patri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\response.py", line 833, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(16170622 bytes read, 30666048 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\patri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\patri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\response.py", line 934, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\response.py", line 905, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\response.py", line 811, in _raw_read
    with self._error_catcher():
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\patri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\response.py", line 729, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(16170622 bytes read, 30666048 more expected)', IncompleteRead(16170622 bytes read, 30666048 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\CyberdropBunkrDownloader-main\dump.py", line 232, in <module>
    get_items_list(session, cdn_list, args.u, args.e, args.w, args.p)
  File "G:\CyberdropBunkrDownloader-main\dump.py", line 54, in get_items_list
    download(session, item['url'], download_path, is_bunkr, item['name'] if not is_bunkr else None)
  File "G:\CyberdropBunkrDownloader-main\dump.py", line 131, in download
    for chunk in r.iter_content(chunk_size=8192):
  File "C:\Users\patri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(16170622 bytes read, 30666048 more expected)', IncompleteRead(16170622 bytes read, 30666048 more expected))
```

**Comment by PaaaulZ** [comment]
I think they are adding some checks to prevent too many requests, looks like they cut the connection off while you were downloading.
I have to figure out what's the limit and eventually add a delay

**Comment by PaaaulZ** [comment]
Should be "fixed" with the new release
